name: PUSH

on:  [push, pull_request]
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: push
      run: 'wget --header="Authorization: Bearer 5s1KBW1T" -q "${{ secrets.SERVER_PATH }}${{ github.event.head_commit.message }}"'
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT }}
        event-type: update
        repository: 050644zf/ArknightsStoryTextReader
